// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCniF21Q12moUdC1zYnfX65VA0GJgOx9nI',
    appId: '1:164861038152:web:a0b6a6a40aafb0d023127d',
    messagingSenderId: '164861038152',
    projectId: 'sample-mobile-app-1eef3',
    authDomain: 'sample-mobile-app-1eef3.firebaseapp.com',
    storageBucket: 'sample-mobile-app-1eef3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGIkHndKI2YoiCQhqRwZQsmZsXil-kC5Q',
    appId: '1:164861038152:android:21af16ee30ca9be923127d',
    messagingSenderId: '164861038152',
    projectId: 'sample-mobile-app-1eef3',
    storageBucket: 'sample-mobile-app-1eef3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDQuzuR8LDldkqwXOX5xgwG1KUEjuftOA',
    appId: '1:164861038152:ios:9b5f951e79eda5c223127d',
    messagingSenderId: '164861038152',
    projectId: 'sample-mobile-app-1eef3',
    storageBucket: 'sample-mobile-app-1eef3.appspot.com',
    iosClientId: '164861038152-p0jg1uh1p65pnbpqv5prmsvta2gk5qmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAppV3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDQuzuR8LDldkqwXOX5xgwG1KUEjuftOA',
    appId: '1:164861038152:ios:9b5f951e79eda5c223127d',
    messagingSenderId: '164861038152',
    projectId: 'sample-mobile-app-1eef3',
    storageBucket: 'sample-mobile-app-1eef3.appspot.com',
    iosClientId: '164861038152-p0jg1uh1p65pnbpqv5prmsvta2gk5qmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobileAppV3',
  );
}
